In [1]:
import torch
import os , pickle
import numpy as np
model_path = "./model_weights_release.pth"
path = "../data/new/agent_0"
files  = os.listdir(path)
data = list()
for file in files:
    file_path = os.path.join(path,file)
    with open(file_path , 'rb') as f:
        data.append(pickle.load(f))

In [1]:
import pickle
model_path = "./audio/audio_weights_release.pth"

In [2]:
with open("../data/new/agent_3/offline_episode_3_759.pkl" , 'rb') as f:
    data = pickle.load(f)

In [3]:
data[0]['rl_pred']

array([0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
data[0]['audio'][1]

array([[ 4.20336566e-09,  3.82821419e-09,  5.88461102e-09, ...,
         1.19369775e-01,  1.29106417e-01,  1.31843269e-01],
       [-2.68184119e-09, -3.01036085e-09, -1.94206518e-09, ...,
        -3.51799093e-02, -2.48818509e-02, -1.40319085e-02]], dtype=float32)

In [9]:
audio = list()
tag = list()
audio_ = data[0]['audio']
tag_ = data[0]['rl_pred']
for index,tag__ in enumerate(tag_):
    if tag__ !=3 and tag__ !=0:
        audio.append(audio_[index])
        tag.append(tag__)

In [10]:
tag

[1, 1, 1, 2, 1, 2, 1, 2, 1, 2]

In [14]:
audio[0]

array([[ 4.20336566e-09,  3.82821419e-09,  5.88461102e-09, ...,
         1.19369775e-01,  1.29106417e-01,  1.31843269e-01],
       [-2.68184119e-09, -3.01036085e-09, -1.94206518e-09, ...,
        -3.51799093e-02, -2.48818509e-02, -1.40319085e-02]], dtype=float32)

In [28]:
from network import Network
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Network().to(device)
model.load_state_dict(torch.load(model_path))
model.eval()
result = model(audio.to(device) , img.to(device))

In [29]:
result

tensor([[ 8.1027e+01, -9.6879e+00,  5.0787e+01, -1.3256e+02],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        [ 9.6061e-01, -1.2225e-01, -8.7205e-02, -5.9272e+00],
        

In [30]:
x = torch.max(result,dim=1)
x

torch.return_types.max(
values=tensor([81.0271,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,
         0.9606,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,  0.9606,
         0.9606,  0.9606,  0.9606,  0.9606], device='cuda:0',
       grad_fn=<MaxBackward0>),
indices=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       device='cuda:0'))

In [ ]:
data

In [ ]:
from network import MyData
from torch.utils.data import DataLoader
dataset = MyData(data)
dataloader = DataLoader(dataset=dataset , batch_size=32 , shuffle=True , collate_fn=dataset.collate_fn)
for batch_idx, (batch_audio, batch_visual, batch_labels) in enumerate(dataloader):
    print(batch_audio.shape)
    print(batch_visual.shape)
    print(batch_labels.shape)
    print(batch_labels)

In [ ]:
from network import MyData
from torch.utils.data import DataLoader
dataset = MyData(data)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True, collate_fn=dataset.collate_fn)
# Example usage of the dataloader
for batch_idx, (audio, visual, labels) in enumerate(dataloader):
    print(f"Batch {batch_idx} labels: {labels}")
    break

In [2]:
from RL import Network
from RL import MyData
from RL import Train
device = torch.device('cuda')
net = Network().to(device)
train = Train()
train.state_net.load_state_dict(torch.load(model_path))
train.state_net.to(device)
state , next_state = train.rl_state(torch.from_numpy(data[0]['audio']).to(device) , torch.from_numpy(data[0]['camera']).to(device))

In [ ]:
state

In [ ]:
next_state.shape

In [ ]:
import torch
a = torch.zeros((61,128))
b = torch.zeros((61,1))
print(a.shape)
print(b.shape)

In [2]:
c = torch.cat((a,b),dim=1)

In [ ]:
c.shape

In [ ]:
path = "../data/new"
files_dir = os.listdir(path)
files_ = list()
files = list()
for file_dir in files_dir:
    files_.append(os.path.join(path,file_dir))
for file_ in files_:
    print(file_)
    for i in os.listdir(file_):
        print(i)
        files.append(os.path.join(file_ ,i))
        print(os.path.join(file_ ,i))

In [ ]:
files

In [ ]:
files_dir

In [ ]:
files_

In [ ]:
os.listdir(files_[0])

In [ ]:
files