In [41]:
import pickle
# model_path = "../checkpoint/audio_weights_release.pth"
model_path = "./audio_weights_fine_tune.pth"
with open("../../data/new/agent_3/offline_episode_3_759.pkl" , 'rb') as f:
    data = pickle.load(f)

In [42]:
data[0]['rl_pred']

array([0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
data[0]['audio'][1]

array([[ 4.20336566e-09,  3.82821419e-09,  5.88461102e-09, ...,
         1.19369775e-01,  1.29106417e-01,  1.31843269e-01],
       [-2.68184119e-09, -3.01036085e-09, -1.94206518e-09, ...,
        -3.51799093e-02, -2.48818509e-02, -1.40319085e-02]], dtype=float32)

In [44]:
audio = list()
tag = list()
audio_ = data[0]['audio']
tag_ = data[0]['rl_pred']
num = 0
for index,tag__ in enumerate(tag_):
    if tag__ !=3 and tag__ !=0:
        audio.append(audio_[index])
        tag.append(tag__)
    if tag__ == 0 and num <=4:
        num +=1
        audio.append(audio_[index])
        tag.append(tag__)

In [45]:
# audio = list()
# tag = list()
# audio_ = data[0]['audio']
# tag_ = data[0]['rl_pred']
# num = 0
# for index,tag__ in enumerate(tag_):
#     if tag__ !=3 and tag__ !=0:
#         audio.append(audio_[index])
#         tag.append(tag__)

In [46]:
tag

[0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2]

In [47]:
audio[1]

array([[ 4.20336566e-09,  3.82821419e-09,  5.88461102e-09, ...,
         1.19369775e-01,  1.29106417e-01,  1.31843269e-01],
       [-2.68184119e-09, -3.01036085e-09, -1.94206518e-09, ...,
        -3.51799093e-02, -2.48818509e-02, -1.40319085e-02]], dtype=float32)

In [48]:
from audio import AudioNet
import torch
import numpy as np
audio = torch.from_numpy(np.array(audio))
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = AudioNet(64 , 4 ,width_dim=128 , height_dim=36).to(device)
model.load_state_dict(torch.load(model_path))
model.eval()
result = model(audio.to(device))

In [49]:
result
x = torch.max(result,dim=1)
x

torch.return_types.max(
values=tensor([1.2027, 1.3043, 2.6780, 2.1472, 1.2604, 1.0736, 1.1995, 1.2094, 1.2798,
        2.1461, 1.0771, 1.1071, 1.0966, 1.1996, 2.6049], device='cuda:0',
       grad_fn=<MaxBackward0>),
indices=tensor([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2], device='cuda:0'))

In [50]:
# [1, 1, 1, 1, 1, 2, 1, 2, 1, 2]
# [1, 1, 1, 1, 1, 2, 1, 2, 1, 2]
# 普通audio_net
# 正确率100%

In [51]:
# [0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0] #result
# [0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2] # tag
# 加上move forward
# 看起来效果不好
# 降低学习率

In [ ]:
# [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2]
# [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2]
# 正确率100%