In [14]:
import pickle
model_path = "./visual_weights_1.pth"
# model_path = "../checkpoint/visual_weights.pth"
with open("../../data/new/agent_3/offline_episode_3_759.pkl" , 'rb') as f:
    data = pickle.load(f)

In [15]:
data[0]['rl_pred']

array([0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 2,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
data[0]['audio'][1]

array([[ 4.20336566e-09,  3.82821419e-09,  5.88461102e-09, ...,
         1.19369775e-01,  1.29106417e-01,  1.31843269e-01],
       [-2.68184119e-09, -3.01036085e-09, -1.94206518e-09, ...,
        -3.51799093e-02, -2.48818509e-02, -1.40319085e-02]], dtype=float32)

In [17]:
data[0]['camera'][1]

array([[[159., 156., 147., 255.],
        [158., 155., 146., 255.],
        [158., 156., 144., 255.],
        ...,
        [152., 147., 133., 255.],
        [150., 147., 132., 255.],
        [151., 148., 133., 255.]],

       [[159., 156., 147., 255.],
        [159., 156., 147., 255.],
        [158., 155., 146., 255.],
        ...,
        [152., 149., 134., 255.],
        [152., 149., 134., 255.],
        [152., 149., 134., 255.]],

       [[160., 157., 148., 255.],
        [160., 157., 147., 255.],
        [160., 157., 147., 255.],
        ...,
        [152., 149., 134., 255.],
        [152., 149., 134., 255.],
        [152., 149., 133., 255.]],

       ...,

       [[226., 218., 209., 255.],
        [226., 218., 209., 255.],
        [228., 219., 211., 255.],
        ...,
        [169., 143., 113., 255.],
        [157., 135., 110., 255.],
        [194., 178., 170., 255.]],

       [[226., 218., 209., 255.],
        [228., 219., 210., 255.],
        [228., 219., 212., 255.],
        .

In [18]:
audio = list()
tag = list()
visual = list()
audio_ = data[0]['audio']
tag_ = data[0]['rl_pred']
visual_ = data[0]['camera']
num = 0
for index,tag__ in enumerate(tag_):
    if tag__ !=3 and tag__ !=0:
        audio.append(audio_[index])
        visual.append(visual_[index])
        tag.append(tag__)
    if tag__ == 0 and num <=4:
        num +=1
        audio.append(audio_[index])
        visual.append(visual_[index])
        tag.append(tag__)
audio.pop(0)
tag.pop(0)
visual.pop(0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0.

In [19]:
tag

[1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2]

In [20]:
audio[1]

array([[ 0.13570994,  0.13118772,  0.12228528, ..., -0.07533199,
        -0.08264603, -0.08182199],
       [-0.0278557 , -0.02046787, -0.01098364, ..., -0.03188229,
        -0.04022564, -0.04896313]], dtype=float32)

In [21]:
visual[0]

array([[[159., 156., 147., 255.],
        [158., 155., 146., 255.],
        [158., 156., 144., 255.],
        ...,
        [152., 147., 133., 255.],
        [150., 147., 132., 255.],
        [151., 148., 133., 255.]],

       [[159., 156., 147., 255.],
        [159., 156., 147., 255.],
        [158., 155., 146., 255.],
        ...,
        [152., 149., 134., 255.],
        [152., 149., 134., 255.],
        [152., 149., 134., 255.]],

       [[160., 157., 148., 255.],
        [160., 157., 147., 255.],
        [160., 157., 147., 255.],
        ...,
        [152., 149., 134., 255.],
        [152., 149., 134., 255.],
        [152., 149., 133., 255.]],

       ...,

       [[226., 218., 209., 255.],
        [226., 218., 209., 255.],
        [228., 219., 211., 255.],
        ...,
        [169., 143., 113., 255.],
        [157., 135., 110., 255.],
        [194., 178., 170., 255.]],

       [[226., 218., 209., 255.],
        [228., 219., 210., 255.],
        [228., 219., 212., 255.],
        .

In [22]:
from visual import VisualNet
import torch
import numpy as np
audio = torch.from_numpy(np.array(audio))
visual = torch.from_numpy(np.array(visual))
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = VisualNet(64 , 4 ,width_dim=128 , height_dim=128).to(device)
model.load_state_dict(torch.load(model_path))
model.eval()
result = model(visual.to(device),audio.to(device))

In [23]:
result

tensor([[  6.4153,   6.7172,   8.8923, -13.7292],
        [  5.3643,   6.6690,   9.3184, -14.0999],
        [  3.6604,   5.2042,   4.1208,  -8.7447],
        [  4.2311,   4.3195,   5.9001, -10.0343],
        [  8.3671,   7.2189,   9.4488, -18.1684],
        [  7.8820,   6.7796,   8.7582, -17.4203],
        [  7.4105,   6.4958,   7.3330, -11.4202],
        [  4.9154,   5.2984,   4.7339,  -9.0667],
        [  4.7041,   5.3330,   4.9158,  -9.5689],
        [  8.5775,   7.4478,   9.6023, -18.6049],
        [  3.8950,   5.0965,   4.6413,  -9.1183],
        [  7.0621,   6.1161,   7.2059, -16.3763],
        [  5.8767,   5.0289,   6.6535, -14.4607],
        [  7.5352,   6.5363,   7.7357, -17.3895]], device='cuda:0',
       grad_fn=<AddmmBackward0>)

In [24]:
result
x = torch.max(result,dim=1)
x

torch.return_types.max(
values=tensor([8.8923, 9.3184, 5.2042, 5.9001, 9.4488, 8.7582, 7.4105, 5.2984, 5.3330,
        9.6023, 5.0965, 7.2059, 6.6535, 7.7357], device='cuda:0',
       grad_fn=<MaxBackward0>),
indices=tensor([2, 2, 1, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2], device='cuda:0'))

In [25]:
[0, 2, 1, 0, 0, 0, 2, 2, 0, 1, 0, 1, 2, 1, 2]
[0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2]
[2, 2, 1, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2]
[1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2]
# 错误率4/15 0.26

[0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2]