In [5]:
import pickle
import os ,re
import numpy as np
import torch
from torch.utils.data import DataLoader
# from avf import MyData
# from dsac import MyData
# from data.newdata import newMyData
# from data.data1 import Data
from data.use_combinencode import Data
from tqdm import tqdm

In [11]:
database_path = ['../../data/database/combinencode_level/combinencode_0' , \
       '../../data/database/combinencode_level/combinencode_1' ,\
        '../../data/database/combinencode_level/combinencode_2']
mydata = Data(database_path=database_path , limit_level=0)

In [12]:
# 第一个就是obs所带来的动作，最后一个动作一定是和前一个一样的，因为visual和上一个相等
def bi(batch_labels , model_action):
    # batch_labels = np.array(batch_labels)
    bi = 0
    for i in range(len(batch_labels)):
        if batch_labels[i] == model_action[i]:
            bi +=1 
    return bi/len(batch_labels)

In [3]:
path_files

['../../data/RL/valdata/RLDATA.log',
 '../../data/RL/valdata/rl_episode_599.pkl',
 '../../data/RL/valdata/rl_episode_598.pkl',
 '../../data/RL/valdata/rl_episode_597.pkl',
 '../../data/RL/valdata/rl_episode_596.pkl',
 '../../data/RL/valdata/rl_episode_595.pkl',
 '../../data/RL/valdata/rl_episode_594.pkl',
 '../../data/RL/valdata/rl_episode_593.pkl',
 '../../data/RL/valdata/rl_episode_592.pkl',
 '../../data/RL/valdata/rl_episode_591.pkl',
 '../../data/RL/valdata/rl_episode_590.pkl',
 '../../data/RL/valdata/rl_episode_589.pkl',
 '../../data/RL/valdata/rl_episode_588.pkl',
 '../../data/RL/valdata/rl_episode_587.pkl',
 '../../data/RL/valdata/rl_episode_586.pkl',
 '../../data/RL/valdata/rl_episode_585.pkl',
 '../../data/RL/valdata/rl_episode_584.pkl',
 '../../data/RL/valdata/rl_episode_583.pkl',
 '../../data/RL/valdata/rl_episode_582.pkl',
 '../../data/RL/valdata/rl_episode_581.pkl',
 '../../data/RL/valdata/rl_episode_580.pkl',
 '../../data/RL/valdata/rl_episode_579.pkl',
 '../../data/RL/va

In [19]:

dataloader = DataLoader(dataset=mydata, batch_size=16, shuffle=True)

In [41]:

# from dsac import AVNet
# from net.network import Actor
# from net.network import Critic
# from net.sac_cql_1 import DiscreteSAC_CQL_1
from train_combinencode_use_level import AVNet
model_path = './checkpoint/DSAC_mutienv_combinencode_level_100000.pth'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
agent =  AVNet(128, 4, 128, 36).to(device)
agent.load_state_dict(torch.load(model_path))
agent.eval()

AVNet(
  (Q_net1): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=4, bias=True)
  )
  (Q_net2): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=4, bias=True)
  )
  (policy_net): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=4, bias=True)
  )
)

In [42]:
batch_data = next(iter(dataloader))
batch_pre_state , batch_next_state, batch_done, batch_reward, batch_labels = batch_data
batch_done = batch_done.to(device)

# state = agent.lstm(batch_pre_audio,batch_pre_visual)
model_action = agent(batch_pre_state)[0].max(-1)[1]

In [ ]:
# model_action = agent(batch_pre_audio.squeeze(1) , batch_pre_visual.squeeze(1))[0]

In [43]:
model_action

tensor([0, 3, 0, 1, 1, 3, 3, 3, 0, 0, 0, 3, 3, 1, 3, 3], device='cuda:0')

In [44]:
batch_labels

tensor([2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0], device='cuda:0')

In [71]:
bi_list = list()
for batch_data in tqdm(dataloader ,desc='dataloder'):
    batch_pre_audio, batch_pre_visual, batch_next_audio , batch_next_visual,batch_done, batch_reward ,batch_labels = batch_data
    # model_action = agent(batch_pre_audio,batch_pre_visual).max(-1)[1].tolist()
    model_action = agent(batch_pre_audio.squeeze(1) , batch_pre_visual.squeeze(1))[2].max(-1)[1]
    bi_list.append(bi(batch_labels=batch_labels , model_action=model_action))
    

dataloder:   0%|          | 0/601 [00:00<?, ?it/s]


RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [13]:
print(f"max_bi : {max(bi_list)},\nmin_bi : {min(bi_list)}, \nmean_bi :{np.array(bi_list).mean()}")

max_bi : 1.0,
min_bi : 0.0, 
mean_bi :0.9494978509535471


In [16]:
a  = torch.zeros((61,2,18000))

In [17]:
torch.all(a == 0)

tensor(True)

In [5]:
# path = '../data/RL/newdone'
def load(path):
    files = os.listdir(path)
    files_path = list()
    for file in files :
        files_path.append(os.path.join(path, file))
    return files_path

In [4]:
files = load(path)

In [5]:
mydata = MyData(path)

FileNotFoundError: [Errno 2] No such file or directory: 'd'

In [4]:
with open(files[0],'rb') as f:
    data = pickle.load(f)

NameError: name 'files' is not defined

In [28]:
preaudio,previsual, nextaudio, nextvisua,done,reward,action = mydata.__getitem__(0)

In [ ]:
np.array_equal(data[0][0]['camera'][1]  , nextvisua)

True

: 

In [1]:
# test dataset
from avn import MyData
path = ['../data/RL/newdone']

In [6]:
files = load(path[0])

In [7]:
files[0]

'../data/RL/newdone/rl_episode_699.pkl'

In [10]:
with open('../data/RL/newdone/rl_episode_699.pkl', 'rb') as f:
    data = pickle.load(f)

In [9]:
data[0][0].keys()

dict_keys(['camera', 'audio', 'step', 'rl_pred', 'rl_logits', 'rl_value', 'reward', 'mask', 'lstm_h', 'lstm_c'])

In [14]:
data[0][0]['reward']

array([  0.       ,  10.       ,   2.4662066,   2.4586916,   2.4483824,
         2.4337363,   2.4119735,  10.       ,   2.416885 ,  10.       ,
         2.4104476,  10.       ,   2.4174547,   2.3424149,  10.       ,
       100.       , 100.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ,   0.       ,   0.       ,   0.       ,   0.       ,
         0.       ], dtype=float32)

In [15]:
data[0][0]['step']

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [47]:
data[0][0]['rl_pred']

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 2,
       0, 1, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2,
       0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
len(data[2])

16

In [3]:
mydata.__len__()

24631
24631
24631
24631
24553
24631
24631


24631

In [12]:
len(data[2])

16

In [6]:
# 核心查看reward， done ， state
preaudio,previsual, nextaudio, nextvisual,done,reward,action   = mydata.__getitem__(24552)

In [7]:
action

1

In [8]:
done

1

In [24]:
for i in range(1000):
    # print(i)
    preaudio,previsual, nextaudio, nextvisual,done,reward,action   = mydata.__getitem__(672+i)

In [25]:
mydata.__len__()

24631

In [19]:
done

0

In [9]:
action

2

In [40]:
data[0][0]['audio'][1]

array([[ 3.75192100e-09,  2.66960276e-09,  7.51610330e-10, ...,
        -6.12057652e-03, -5.28840907e-03,  1.39715587e-04],
       [ 1.42392553e-09, -1.46208753e-10, -2.45285459e-09, ...,
         6.69605145e-03,  7.13925110e-03,  1.08815385e-02]], dtype=float32)

In [41]:
data[0][0]['camera'][1]

array([[[149., 146., 129., 255.],
        [149., 147., 129., 255.],
        [149., 148., 130., 255.],
        ...,
        [143., 144., 128., 255.],
        [143., 144., 128., 255.],
        [143., 144., 128., 255.]],

       [[148., 147., 127., 255.],
        [148., 147., 127., 255.],
        [148., 147., 127., 255.],
        ...,
        [143., 144., 128., 255.],
        [143., 144., 128., 255.],
        [141., 142., 126., 255.]],

       [[150., 146., 127., 255.],
        [148., 147., 127., 255.],
        [148., 147., 127., 255.],
        ...,
        [143., 144., 127., 255.],
        [141., 142., 126., 255.],
        [141., 142., 128., 255.]],

       ...,

       [[ 60.,  55.,  45., 255.],
        [ 59.,  54.,  45., 255.],
        [ 60.,  55.,  45., 255.],
        ...,
        [107., 104.,  86., 255.],
        [110., 107.,  91., 255.],
        [110., 107.,  91., 255.]],

       [[ 72.,  63.,  51., 255.],
        [ 72.,  63.,  51., 255.],
        [ 76.,  68.,  55., 255.],
        .

In [16]:
print(np.array_equal(np.array(nextaudio) , data[0][0]['audio'][17]))

False


In [18]:
print(np.array_equal(np.array(nextvisual) , data[0][0]['camera'][17]))

True


In [19]:
reward

100.0

In [24]:
done

0

In [1]:
import torch
a = torch.Tensor([[1,2,3,4],[5,6,7,8]])
b = torch.Tensor([[2,1,4,3],[6,5,8,7]])

In [2]:
a

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [3]:
b

tensor([[2., 1., 4., 3.],
        [6., 5., 8., 7.]])

In [4]:
torch.min(a,b)

tensor([[1., 1., 3., 3.],
        [5., 5., 7., 7.]])

In [15]:
import torch
a = [1,1,1,1]
torch.tensor(a)

tensor([1, 1, 1, 1])

In [4]:
from net.avf import AVFNet
import torch
device = torch.device('cuda')
avf = AVFNet(hid_dim=128 , out_put=4 ,width_dim=128 , height_dim=36).to(device)
model_path = '../checkpoint/avnf_finnal_1.pth'
avf.load_state_dict(torch.load(model_path))
avf.eval()

AVFNet(
  (audio): Sequential(
    (0): Conv2d(2, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU()
    (4): Flatten(start_dim=1, end_dim=-1)
    (5): Linear(in_features=294912, out_features=128, bias=True)
    (6): ReLU()
    (7): Linear(in_features=128, out_features=64, bias=True)
  )
  (visual): Sequential(
    (0): Conv2d(4, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU()
    (4): Flatten(start_dim=1, end_dim=-1)
    (5): Linear(in_features=1048576, out_features=128, bias=True)
    (6): ReLU()
    (7): Linear(in_features=128, out_features=64, bias=True)
  )
  (mask): Sequential(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=128, bias=True)
  )
  (action_net): Sequential(
    (0): Lin

In [6]:
# from dsac import AVNet
# from net.network import Actor
# from net.network import Critic
# from net.sac_cql_1 import DiscreteSAC_CQL_1
from dsac import AVNet
model_path = './checkpoint/DSAC_F_2_260000.pth'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
agent =  AVNet(128, 4, 128, 36).to(device)
agent.load_state_dict(torch.load(model_path))
agent.eval()

AVNet(
  (avf): AVFNet(
    (audio): Sequential(
      (0): Conv2d(2, 32, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
      (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
      (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (4): Conv2d(32, 64, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
      (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (visual): Sequential(
      (0): Conv2d(4, 32, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
      (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(1, 1))
      (3): MaxPool2d(kernel_s

In [72]:
batch_data = next(iter(dataloader))
batch_pre_audio, batch_pre_visual, batch_next_audio , batch_next_visual,batch_done, batch_reward ,batch_labels = batch_data
# print(batch_pre_audio.squeeze(1).shape)
# state = agent.lstm(batch_pre_audio,batch_pre_visual)
# model_action = agent(batch_pre_audio.squeeze(1) , batch_pre_visual.squeeze(1))[2].max(-1)[1]

In [73]:
model_action = agent(batch_pre_audio.squeeze(1) , batch_pre_visual.squeeze(1))[2]

In [74]:
model_action.max(-1)[1]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       device='cuda:0')

In [75]:
batch_labels

tensor([[2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2,
         0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 2, 2, 0, 3]],
       device='cuda:0')

In [18]:
bi_list = list()
for batch_data in tqdm(dataloader ,desc='dataloder'):
    batch_pre_audio, batch_pre_visual, batch_next_audio , batch_next_visual,batch_done, batch_reward ,batch_labels = batch_data
    batch_next_visual = torch.stack(batch_next_visual).to(device).float()
    batch_next_audio = torch.stack(batch_next_audio).to(device).float()
    batch_pre_audio = torch.stack(batch_pre_audio).to(device).float()
    batch_pre_visual = torch.stack(batch_pre_visual).to(device).float()
    # model_action = agent(batch_pre_audio,batch_pre_visual).max(-1)[1].tolist()
    model_action = avf(batch_pre_audio.squeeze(1) , batch_pre_visual.squeeze(1)).max(-1)[1].tolist()
    bi_list.append(bi(batch_labels=batch_labels , model_action=model_action))

dataloder:   0%|          | 0/189 [00:00<?, ?it/s]

torch.Size([16, 128, 128, 4])


dataloder:   1%|          | 1/189 [00:03<09:27,  3.02s/it]

torch.Size([25, 128, 128, 4])


dataloder:   1%|          | 2/189 [00:07<12:53,  4.13s/it]

torch.Size([28, 128, 128, 4])


dataloder:   2%|▏         | 3/189 [00:11<12:40,  4.09s/it]

torch.Size([27, 128, 128, 4])


dataloder:   2%|▏         | 4/189 [00:12<08:48,  2.85s/it]

torch.Size([16, 128, 128, 4])


dataloder:   3%|▎         | 5/189 [00:13<06:17,  2.05s/it]

torch.Size([20, 128, 128, 4])


dataloder:   3%|▎         | 6/189 [00:16<07:06,  2.33s/it]

torch.Size([26, 128, 128, 4])


dataloder:   4%|▎         | 7/189 [00:17<05:40,  1.87s/it]

torch.Size([35, 128, 128, 4])


dataloder:   4%|▍         | 8/189 [00:19<06:06,  2.02s/it]

torch.Size([15, 128, 128, 4])


dataloder:   5%|▍         | 9/189 [00:22<06:58,  2.32s/it]

torch.Size([31, 128, 128, 4])


dataloder:   6%|▌         | 11/189 [00:26<05:50,  1.97s/it]

torch.Size([27, 128, 128, 4])
torch.Size([20, 128, 128, 4])


dataloder:   7%|▋         | 13/189 [00:34<09:02,  3.08s/it]

torch.Size([24, 128, 128, 4])
torch.Size([36, 128, 128, 4])


dataloder:   7%|▋         | 14/189 [00:35<06:58,  2.39s/it]

torch.Size([32, 128, 128, 4])


dataloder:   8%|▊         | 15/189 [00:38<07:28,  2.58s/it]

torch.Size([21, 128, 128, 4])


dataloder:   8%|▊         | 16/189 [00:39<06:28,  2.25s/it]

torch.Size([35, 128, 128, 4])


dataloder:   9%|▉         | 17/189 [00:40<05:24,  1.89s/it]

torch.Size([16, 128, 128, 4])


dataloder:  10%|▉         | 18/189 [00:41<04:41,  1.65s/it]

torch.Size([17, 128, 128, 4])


dataloder:  10%|█         | 19/189 [00:44<05:30,  1.94s/it]

torch.Size([30, 128, 128, 4])


dataloder:  11%|█         | 20/189 [00:51<09:27,  3.36s/it]

torch.Size([34, 128, 128, 4])


dataloder:  11%|█         | 21/189 [00:55<10:26,  3.73s/it]

torch.Size([10, 128, 128, 4])


dataloder:  12%|█▏        | 22/189 [00:57<08:34,  3.08s/it]

torch.Size([39, 128, 128, 4])


dataloder:  12%|█▏        | 23/189 [00:58<07:19,  2.65s/it]

torch.Size([27, 128, 128, 4])


dataloder:  13%|█▎        | 25/189 [01:01<05:31,  2.02s/it]

torch.Size([27, 128, 128, 4])
torch.Size([40, 128, 128, 4])


dataloder:  14%|█▍        | 26/189 [01:02<04:51,  1.79s/it]

torch.Size([40, 128, 128, 4])


dataloder:  15%|█▍        | 28/189 [01:06<04:42,  1.75s/it]

torch.Size([10, 128, 128, 4])
torch.Size([26, 128, 128, 4])


dataloder:  15%|█▌        | 29/189 [01:12<07:36,  2.85s/it]

torch.Size([16, 128, 128, 4])


dataloder:  16%|█▌        | 30/189 [01:13<06:00,  2.26s/it]

torch.Size([38, 128, 128, 4])


dataloder:  17%|█▋        | 32/189 [01:24<10:02,  3.84s/it]

torch.Size([13, 128, 128, 4])
torch.Size([21, 128, 128, 4])


dataloder:  17%|█▋        | 33/189 [01:27<09:09,  3.52s/it]

torch.Size([38, 128, 128, 4])


dataloder:  18%|█▊        | 34/189 [01:29<07:54,  3.06s/it]

torch.Size([24, 128, 128, 4])


dataloder:  19%|█▊        | 35/189 [01:30<06:01,  2.35s/it]

torch.Size([24, 128, 128, 4])


dataloder:  19%|█▉        | 36/189 [01:31<05:10,  2.03s/it]

torch.Size([20, 128, 128, 4])


dataloder:  20%|█▉        | 37/189 [01:35<06:56,  2.74s/it]

torch.Size([15, 128, 128, 4])


dataloder:  20%|██        | 38/189 [01:37<05:56,  2.36s/it]

torch.Size([35, 128, 128, 4])


dataloder:  21%|██        | 39/189 [01:38<04:49,  1.93s/it]

torch.Size([27, 128, 128, 4])


dataloder:  21%|██        | 40/189 [01:44<07:40,  3.09s/it]

torch.Size([36, 128, 128, 4])


dataloder:  22%|██▏       | 41/189 [01:50<10:24,  4.22s/it]

torch.Size([12, 128, 128, 4])


dataloder:  22%|██▏       | 42/189 [01:51<07:37,  3.11s/it]

torch.Size([19, 128, 128, 4])


dataloder:  23%|██▎       | 43/189 [01:52<06:02,  2.48s/it]

torch.Size([37, 128, 128, 4])


dataloder:  23%|██▎       | 44/189 [01:55<06:43,  2.78s/it]

torch.Size([17, 128, 128, 4])


dataloder:  24%|██▍       | 45/189 [01:57<05:32,  2.31s/it]

torch.Size([15, 128, 128, 4])


dataloder:  24%|██▍       | 46/189 [01:58<04:46,  2.00s/it]

torch.Size([27, 128, 128, 4])


dataloder:  25%|██▍       | 47/189 [02:02<06:12,  2.62s/it]

torch.Size([35, 128, 128, 4])


dataloder:  25%|██▌       | 48/189 [02:06<07:14,  3.08s/it]

torch.Size([35, 128, 128, 4])


dataloder:  26%|██▌       | 49/189 [02:08<06:25,  2.75s/it]

torch.Size([36, 128, 128, 4])


dataloder:  26%|██▋       | 50/189 [02:15<09:10,  3.96s/it]

torch.Size([30, 128, 128, 4])


dataloder:  27%|██▋       | 51/189 [02:16<06:52,  2.99s/it]

torch.Size([18, 128, 128, 4])


dataloder:  28%|██▊       | 52/189 [02:16<05:12,  2.28s/it]

torch.Size([10, 128, 128, 4])


dataloder:  28%|██▊       | 53/189 [02:18<04:57,  2.18s/it]

torch.Size([36, 128, 128, 4])


dataloder:  29%|██▊       | 54/189 [02:20<04:48,  2.13s/it]

torch.Size([30, 128, 128, 4])


dataloder:  29%|██▉       | 55/189 [02:22<04:39,  2.08s/it]

torch.Size([38, 128, 128, 4])


dataloder:  30%|██▉       | 56/189 [02:29<07:54,  3.56s/it]

torch.Size([38, 128, 128, 4])


dataloder:  30%|███       | 57/189 [02:34<08:20,  3.79s/it]

torch.Size([14, 128, 128, 4])


dataloder:  31%|███       | 58/189 [02:35<06:28,  2.96s/it]

torch.Size([35, 128, 128, 4])


dataloder:  31%|███       | 59/189 [02:38<06:22,  2.94s/it]

torch.Size([17, 128, 128, 4])


dataloder:  32%|███▏      | 60/189 [02:38<04:41,  2.18s/it]

torch.Size([37, 128, 128, 4])


dataloder:  32%|███▏      | 61/189 [02:39<03:43,  1.75s/it]

torch.Size([26, 128, 128, 4])


dataloder:  33%|███▎      | 62/189 [02:41<04:03,  1.92s/it]

torch.Size([8, 128, 128, 4])


dataloder:  33%|███▎      | 63/189 [02:42<03:12,  1.53s/it]

torch.Size([18, 128, 128, 4])


dataloder:  34%|███▍      | 64/189 [02:44<03:46,  1.82s/it]

torch.Size([28, 128, 128, 4])


dataloder:  34%|███▍      | 65/189 [02:46<04:05,  1.98s/it]

torch.Size([29, 128, 128, 4])


dataloder:  35%|███▍      | 66/189 [02:48<04:02,  1.97s/it]

torch.Size([11, 128, 128, 4])


dataloder:  35%|███▌      | 67/189 [02:51<04:06,  2.02s/it]

torch.Size([7, 128, 128, 4])


dataloder:  36%|███▌      | 68/189 [02:51<03:11,  1.58s/it]

torch.Size([17, 128, 128, 4])


dataloder:  37%|███▋      | 69/189 [02:53<03:26,  1.72s/it]

torch.Size([33, 128, 128, 4])


dataloder:  37%|███▋      | 70/189 [02:58<05:24,  2.73s/it]

torch.Size([24, 128, 128, 4])


dataloder:  38%|███▊      | 71/189 [03:03<06:39,  3.39s/it]

torch.Size([28, 128, 128, 4])


dataloder:  38%|███▊      | 72/189 [03:05<05:50,  2.99s/it]

torch.Size([23, 128, 128, 4])


dataloder:  39%|███▊      | 73/189 [03:12<07:54,  4.09s/it]

torch.Size([21, 128, 128, 4])


dataloder:  39%|███▉      | 74/189 [03:16<07:56,  4.14s/it]

torch.Size([25, 128, 128, 4])


dataloder:  40%|███▉      | 75/189 [03:19<06:53,  3.63s/it]

torch.Size([31, 128, 128, 4])


dataloder:  40%|████      | 76/189 [03:20<05:43,  3.04s/it]

torch.Size([31, 128, 128, 4])


dataloder:  41%|████      | 77/189 [03:21<04:35,  2.46s/it]

torch.Size([32, 128, 128, 4])


dataloder:  42%|████▏     | 79/189 [03:23<02:59,  1.63s/it]

torch.Size([11, 128, 128, 4])
torch.Size([30, 128, 128, 4])


dataloder:  42%|████▏     | 80/189 [03:25<03:15,  1.79s/it]

torch.Size([34, 128, 128, 4])


dataloder:  43%|████▎     | 81/189 [03:27<02:55,  1.62s/it]

torch.Size([30, 128, 128, 4])


dataloder:  43%|████▎     | 82/189 [03:28<02:55,  1.64s/it]

torch.Size([18, 128, 128, 4])


dataloder:  44%|████▍     | 83/189 [03:30<02:52,  1.63s/it]

torch.Size([33, 128, 128, 4])


dataloder:  44%|████▍     | 84/189 [03:34<03:56,  2.26s/it]

torch.Size([22, 128, 128, 4])


dataloder:  45%|████▍     | 85/189 [03:36<04:07,  2.38s/it]

torch.Size([12, 128, 128, 4])


dataloder:  46%|████▌     | 86/189 [03:38<03:34,  2.08s/it]

torch.Size([29, 128, 128, 4])


dataloder:  46%|████▌     | 87/189 [03:39<03:17,  1.94s/it]

torch.Size([31, 128, 128, 4])


dataloder:  47%|████▋     | 88/189 [03:40<02:40,  1.59s/it]

torch.Size([22, 128, 128, 4])


dataloder:  47%|████▋     | 89/189 [03:43<03:14,  1.95s/it]

torch.Size([31, 128, 128, 4])


dataloder:  48%|████▊     | 90/189 [03:45<03:29,  2.12s/it]

torch.Size([13, 128, 128, 4])


dataloder:  48%|████▊     | 91/189 [03:48<03:29,  2.13s/it]

torch.Size([17, 128, 128, 4])


dataloder:  49%|████▊     | 92/189 [03:50<03:22,  2.09s/it]

torch.Size([14, 128, 128, 4])


dataloder:  49%|████▉     | 93/189 [03:54<04:02,  2.52s/it]


KeyboardInterrupt: 

In [20]:
max(bi_list)

0.8857142857142857

In [21]:
np.array(bi_list).mean()

0.6224322536943955